# Generated by Django 2.1.1 on 2018-09-23 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180912_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 14, 34, 53, 157198, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_slug',
            field=models.SlugField(unique=True),
        ),
    ]
