# Generated by Django 2.1.1 on 2018-09-23 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180923_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url_slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(default=datetime.datetime(2018, 9, 23, 16, 31, 42, 672752, tzinfo=utc), verbose_name='created ad')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 16, 31, 42, 654762, tzinfo=utc), verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
