# Generated by Django 2.2.2 on 2019-06-16 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181001_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created ad'),
        ),
    ]
